secrets:
  ssh_private_key:
    file: secrets/ssh_private_key.pem

networks:
  default:

services:
  tunnel:
    image: ghcr.io/n0rthernl1ghts/ssh-tunnel:latest
    build:
      context: .
    deploy:
      restart_policy:
        condition: any
    expose:
      - 5100
    environment:
      LOCAL_SERVICE_PORT: 5100
      REMOTE_SERVICE_HOST: 'localhost'
      REMOTE_SERVICE_PORT: 3306
      REMOTE_SSH_HOST: '123.123.123.123'
      REMOTE_SSH_PORT: 22
    secrets:
      - ssh_private_key
    cap_drop:
      - FSETID
      - KILL
      - SETPCAP
      - NET_BIND_SERVICE
      - NET_RAW
      - SYS_CHROOT
      - MKNOD
      - AUDIT_WRITE
      - SETFCAP
    networks:
      - default
