version: '3.7'

services:
  tunnel:
    image: ghcr.io/n0rthernl1ghts/ssh-tunnel:latest
    build:
      context: .
    expose:
      - 5100
    environment:
      SERVICE_EXPOSE_PORT: 5100
      TUNNEL_SERVICE: 'localhost:3306'
      SSH_HOST: '123.123.123.123'
      SSH_PORT: 22
    cap_drop:
      - FSETID
      - KILL
      - SETPCAP
      - NET_BIND_SERVICE
      - NET_RAW
      - SYS_CHROOT
      - MKNOD
      - AUDIT_WRITE
      - SETFCAP
    networks:
      - default
    volumes:
      - "/path/to/ssh-key/id_ed25519:/secret/keyfile:ro"
      - "/path/to/ssh-key/id_ed25519-cert:/secret/keyfile-cert:ro"
    restart: "always"

networks:
  default: