version: '3.7'

services:
  tunnel:
    image: nlss/ssh-tunnel
    build:
      context: .
    init: true
    expose:
      - 5100
    environment:
      SERVICE_EXPOSE_PORT: 5100
      TUNNEL_SERVICE: 'localhost:3306'
      SSH_HOST: '123.123.123.123'
      SSH_PORT: 22
      TINI_VERBOSITY: 3
    cap_drop:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - SETGID
      - SETUID
      - SETPCAP
      - NET_BIND_SERVICE
      - NET_RAW
      - SYS_CHROOT
      - MKNOD
      - AUDIT_WRITE
      - SETFCAP
    networks:
      - default
    volumes:
      - "/path/to/ssh-key/id_ed25519:/secret/keyfile"
      - "/path/to/ssh-key/id_ed25519-cert:/secret/keyfile-cert"
    restart: "always"

networks:
  default: