#!/command/with-contenv bash
# shellcheck shell=bash

# init-prepare-ssh-keys main
main() {
    # This will prepend service name to all output from here
    exec > >(while read -r line; do echo "[init-prepare-ssh-keys] ${line}"; done) 2>&1

    echo "Preparing ssh keyfile"

    if [ -z "${SSH_PRIVATE_KEY}" ]; then
        echo "Error: Couldn't load private key file"
        return 1
    fi

    echo "Private ssh key file loaded"

    # Prepare ssh keyfile
    printf "%s\n" "${SSH_PRIVATE_KEY}" >"/app/.ssh/keyfile"
    chmod 0600 /app/.ssh/keyfile

    if [ -n "${SSH_KEYFILE_CERT}" ]; then
        echo "Certificate file found. Enabling"
        printf "%s\n" "${SSH_KEYFILE_CERT}" >"/app/.ssh/keyfile-cert"
        chmod 0600 "/app/.ssh/keyfile-cert"
    fi

    attr /app/ true tunnel:tunnel 0770 2771
}
main
