#!/usr/bin/with-contenv sh

TUNNEL_SERVICE="${TUNNEL_SERVICE:-}"
REMOTE_SSH_HOST="${SSH_HOST:-}"
REMOTE_SSH_PORT="${SSH_PORT:-22}"
REMOTE_SSH_USER="${SSH_USER:-root}"
SERVICE_EXPOSE_PORT="${SERVICE_EXPOSE_PORT:-5100}"

if [ -z "${TUNNEL_SERVICE}" ]; then
  echo "> Error: Environment variable TUNNEL_SERVICE missing"
  exit 1
fi

if [ -z "${REMOTE_SSH_HOST}" ]; then
  echo "> Error: Environment variable REMOTE_SSH_HOST missing"
  exit 1
fi

if [ "${SERVICE_EXPOSE_PORT}" -lt 1024 ]; then
  echo "> Error: SERVICE_EXPOSE_PORT must be 1024 or larger. Ports below this value are privileged."
  exit 1
fi

# Start the ssh tunnel process
s6-setuidgid "tunnel" "/usr/bin/ssh" \
  -N -L \
  "0.0.0.0:${SERVICE_EXPOSE_PORT}:${TUNNEL_SERVICE}" \
  "${REMOTE_SSH_USER}@${REMOTE_SSH_HOST}" \
  -p "${REMOTE_SSH_PORT}"