#!/usr/bin/with-contenv sh

TUNNEL_SERVICE="${TUNNEL_SERVICE:?TUNNEL_SERVICE is required}"
REMOTE_SSH_HOST="${SSH_HOST:?REMOTE_SSH_HOST is required}"
REMOTE_SSH_PORT="${SSH_PORT:-22}"
REMOTE_SSH_USER="${SSH_USER:-root}"
SERVICE_EXPOSE_PORT="${SERVICE_EXPOSE_PORT:-5100}"

# Start the ssh tunnel process
s6-setuidgid "tunnel" "/usr/bin/ssh" \
  -N -L \
  "0.0.0.0:${SERVICE_EXPOSE_PORT}:${TUNNEL_SERVICE}" \
  "${REMOTE_SSH_USER}@${REMOTE_SSH_HOST}" \
  -p "${REMOTE_SSH_PORT}"