name: Build stable multiarch image

on:
  workflow_dispatch:
  schedule:
    - cron: "20 4 * * */7"
  push:
    branches: master
    paths:
      - .github/workflows/image.yml  # This workflow file itself
      - .dockerignore
      - Dockerfile
      - build/docker-bake.hcl
      - rootfs/**
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 16
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.PAT_TOKEN}}
      -
        name: Build and push
        uses: docker/bake-action@v6.8.0
        with:
          files: build/docker-bake.hcl
          push: true